prep/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "prep"



urlpatterns = [
    path('',views.home, name='home'),
    path('signup/', views.RegisterView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/',views.LogoutView.as_view(), name='logout'),
    path('construction/', views.construction, name='construction'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
urlpatterns = [
    path('',views.home, name='home'),
    path('signup/', views.sign_up, name="signup"),
    path('login/', views.log_in, name="login"),
    path('logout/',views.log_out, name='logout'),
]



'''

prepnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

def yo(request):

    return HttpResponse("something")



urlpatterns = [
    path('', include("codetest.urls")),
    path('', include("prep.urls")),
    path('', include("team.urls")),
    path('', include("timeline.urls")),
    path('', include("profiles.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/upload/create.html
{% extends 'base_html.html' %}


{% block content %}
    {% if user.is_authenticated %}
        <center>
            <p class="lead">Upload Your work</p>
            <hr class="my-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table><br>
                <button type="submit" class="btn btn-outline-primary my-2 my-sm-0" name="register">Upload</button>
            </form>
        </center>
    {% else %}
        <br><br>
        <h3>Login in first, <a href="{% url 'prep:login' %}">click here</a></h3>
    {% endif %}
{% endblock %}

templates/upload/details.html
{% extends 'base_html.html' %}
{% load static %}

{% block replace %}
    <CENTER>
        <div class="jumbotron">
            <h1><br>Hello {{ user }}</h1>
                <p>its an awesome project</p>
                    <hr class="my-4">

                    <img src="{{ MEDIA_URL }}{{ user_pr.display_picture.url }}" class="image_responsive" width="150px" height="200px">

                <p>You have learned some awesome technologies like {{ user_pr.technologies }}</p>
        </div>
    </CENTER>
{% endblock %}

templates/upload/error.html
{% extends 'base_html.html' %}

{% block content %}
<br><br>
    <h3>I guess this wasn't an image file but don't worry am here, just <a href="/upload/">click here</a> to try again</h3>
{% endblock %}

templates/upload/uploaded.html
{% extends 'base_html.html' %}
{% load static %}

{% block replace %}
    <CENTER>
        <div class="jumbotron">
            <h1><br>Hello {{ user }}</h1>
                <p>its an awesome project</p>
                <hr class="my-4">
                        <img src="{{ post.display_picture.url }}" class="image_responsive" width="150px" height="200px"><br>
                        <p>{{ user_pr.display_picture.url }} uploaded by {{ user }} {{ user_pr.user }}</p><br>

                     <img src="{{ MEDIA_URL }}{{ user_pr.display_picture.url }}" class="image_responsive" width="150px" height="200px">

                <p>You have learned some awesome technologies like {{ user_pr.technologies }}</p>
        </div>
    </CENTER>
{% endblock %}