prep/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "prep"



urlpatterns = [
    path('',views.home, name='home'),
    path('signup/', views.RegisterView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/',views.LogoutView.as_view(), name='logout'),
    path('construction/', views.construction, name='construction'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
urlpatterns = [
    path('',views.home, name='home'),
    path('signup/', views.sign_up, name="signup"),
    path('login/', views.log_in, name="login"),
    path('logout/',views.log_out, name='logout'),
]



'''

prepnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

def yo(request):

    return HttpResponse("something")



urlpatterns = [
    path('', include("codetest.urls")),
    path('', include("prep.urls")),
    path('', include("team.urls")),
    path('', include("timeline.urls")),
    path('', include("profiles.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/base_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>PrepNet</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>


    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link href='//fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>


    <link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster Two" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    </head>
<body>
    {% include 'navbar.html' %}
    <div class="wrapper form-group add-left" style="text-align:center; font-size:15px;">
        {% block content %}
        {% endblock %}
    </div>
<div class="wrapper form-group"  style="text-align:center;">
    {% block replace %}
    {% endblock %}

</div>

</body>
</html>

templates/construction.html
{% extends 'base_html.html' %}
{% load static %}
{% block replace %}

{% if user.is_authenticated %}
    <br><code style="font-size:300%">Construction work going on......</code><br><br>


    <i class="fa fa-spinner fa-pulse fa-5x"></i><br>

    <small >Go back to Timeline,<a href="/timeline/">click here</a></small>
{% else %}

   <br><code style="font-size:300%">Login first Sir.......<a href="/login/">click here</a></code><br><br>
{% endif %}

{% endblock %}

templates/navbar.html
{% load static %}



<nav class="navz navbar navbar-expand-md navbar-light fixed-top bg-light" id="yup" >
      <div class="container">
        <a class="navbar-brand" href="{% url 'prep:home' %}"><img src="{% static 'logo0.png' %}" width="90px" height="50px" alt="Prep-Net"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavId">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/timeline">Timeline</a>
            </li>

            {% else %}

            {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item">
              <form class="form-inline my-2 my-lg-0" action="/search?st" >
                <input class="form-control mr-sm-2" type="Search" placeholder="Search Friends" aria-label="Search" name="search" >
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </li>

            <li class="nav-item dis">
              <a class="nav-link" href="/myprofile/">My Profile</a>
            </li>
            <li class="nav-item dis">
              <a href="/upload/" class="nav-link">Add your project</a>

            </li>
            <li class="nav-item dis">
              <a href="/timeline/test/" class="nav-link">Amcat Practice</a>
            </li>
            <li class="nav-item dis">

              <a href="/timeline/team/" class="nav-link">Make a Team</a>

            </li>
            <li class="nav-item dis">
              <a href="/timeline/team/allteams/" class="nav-link">Show All Teams</a>
            </li>
            <li class="nav-item dropdown multi-level-dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="/profile/myprojects">My Projects</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/logout">Log out</a>
                  </div>
            </li>





            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/signup">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      <dir class="top"></dir>

templates/sidebar.html
{% load static %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">



<div class="sidebar sidelw border-left border-right disn" >


  <a href="/upload/" class="border-bottom btn-social btn-behance hoverWrapper"><i class="fas fa-gear fa-3x"></i>
   <code class="hoverShow1 k">Add your project</code>
  </a>

  <a href="/timeline/test/" class="border-bottom btn-social btn-behance hoverWrapper"><i class="fas fa-code fa-3x"></i>
   <code class="hoverShow1 k">Amcat Practice</code>
  </a>
  <a href="/timeline/team/" class="border-bottom btn-social btn-behance hoverWrapper"><i class="fas fa-user-plus fa-3x"></i>
   <code class="hoverShow1 k">Make a Team </code>
  </a>
  <a href="/timeline/team/allteams/" class="border-bottom btn-social btn-behance hoverWrapper"><i class="fas fa-users fa-3x"></i>
   <code class="hoverShow1 k">Show All Teams </code>
  </a>

</div>

<div class="r sidebar border-left">
    <a ><img class="rounded-circle border" src="{{ dp.display_picture.url }}" height="200px" width="200px"></a>
    <a style="font-family:" href="/myprofile/">My Profile</a>
    <a class="btn btn-outline-primary" style="display: -webkit-inline-box; width:30%; font-family:sofia" href="/logout/">Logout</a><br><hr><br>
    <div><code>Number of pages where construction work is going on: 3</code></div>

</div>